source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'NNFirebaseResultsController_Example', :exclusive => true do
  pod 'NNFirebaseResultsController', :path => '../'
end

target 'NNFirebaseResultsController_Tests', :exclusive => true do
  pod 'NNFirebaseResultsController', :path => '../'

  
end
