source 'https://github.com/noughts/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'NNFirebaseResultsController_Example' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'NNFirebaseResultsController', :path => '../'

  # Pods for NNFirebaseResultsController_Example
  pod "NBULog"
  pod "MBProgressHUD"
end
